name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number: 
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
  xx: 
    description: "xx"    
    value: ${{ github.action_path }}
  total-output: 
    description: "Total output"
    value: Hello ${{ inputs.who-to-greet }} Random ${{ steps.random-number-generator.outputs.random-id }} Trail ${{ steps.goodbyeVar.outputs.goodbye-id }} Path ${{ github.action_path }}
runs:
  using: "composite"
  steps: 
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - run: chmod +x ${{ github.action_path }}/goodbye.sh
      shell: bash  
    - id: scriptOutput 
      run: ${{ github.action_path }}/goodbye.sh
      shell: bash
    - id: goodbyeVar
      run: echo "::set-output name=goodbye-id::$(echo $GOODBYE_VAR)"
      shell: bash    