name: Test internal action-a

on:
    workflow_dispatch:
      branches: [ master ]

jobs:
    hello_world_job:
        runs-on: ubuntu-latest
        name: A job to say hello
        steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: see contents of current directory
          run: |
            echo ls "/home/runner/work/MercuryHealthCore/MercuryHealthCore/.github/actions/action-a"
            ls "/home/runner/work/MercuryHealthCore/MercuryHealthCore/.github/actions/action-a"

        - name: run action-a
          id: foo
          uses: ./.github/actions/action-a
          with:
            who-to-greet: 'Mona the Octocat'
        - run: echo random-number ${{ steps.foo.outputs.random-number }} 
          shell: bash
        - run: echo total-output ${{ steps.foo.outputs.total-output }} 
          shell: bash                                        

