name: Test for VS Internals

on:
  workflow_dispatch:
    branches: [ master ]

    
jobs:

   testStuffOut:
     name:   testStuffOut

     runs-on: windows-latest

     steps:
      - name: see if msbuild is installed
        run: |
          echo ls msbuild
          ls "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\\MSBuild\Current\Bin"

   # build database schema, build artifact is the dacpac
   buildDatabase:
    name:   buildDatabase    

    runs-on: windows-latest

    steps:
    # checkout code from repo
    - name: checkout repo
      uses: actions/checkout@v1

    - name: see contents of current directory
      run: |
        echo ls "./"
        ls "./"

    - name: see if msbuild is installed
      run: |
          echo ls msbuild
          ls "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\\MSBuild\Current\Bin\MSBuild.exe"
     

    # use msbuild to build VS solution which has the SSDT project
    - name: build solution
      run: |
            echo "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\\MSBuild\Current\Bin\MSBuild.exe MercuryHealthCore.sln -target:MercuryHealthDB:Rebuild"
            "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" MercuryHealthCore.sln -target:MercuryHealthDB:Rebuild


       