name: Test for VS Internals

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  testStuffOut:

    runs-on: windows-latest

    steps:
      - name: see if msbuild is installed
        run: |
          echo ls msbuild
          ls "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\\MSBuild\Current\Bin"
       