name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: Build with dotnet
      run: |
        echo ls
        ls
        dotnet build Web/MercuryHealthCore.csproj --configuration Release
  
    - name: Test with dotnet
      run: dotnet test Web/MercuryHealthCore.csproj --configuration Release

    - name: Package everything up with dotnet
      run: dotnet publish Web/MercuryHealthCore.csproj --configuration Release    
      
    - name: test variables
      run: echo GITHUB_WORKSPACE = ${GITHUB_WORKSPACE}

    - name: publish build artifacts back to GitHub
      uses: actions/upload-artifact@master
      with:
        name: webapp
        path: Web/bin/Release/netcoreapp2.2/publish      
